import os

dir_path = r"C:\Users\pierr\Documents\products\publix group\Publix webbplats\site\sv"

def replace_in_file(filename, replacements):
    filepath = os.path.join(dir_path, filename)
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for old, new in replacements:
        if old not in content:
            print(f"WARNING: '{old}' not found in {filename}")
        content = content.replace(old, new)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

common_nav = [
    ('>Home<', '>Hem<'),
    ('>Why PubliX<', '>Varför PubliX<'),
    ('>About<', '>Om oss<'),
    ('>Team<', '>Team<'),
    ('>Companies<', '>Bolag<'),
    ('>News<', '>Nyheter<'),
    ('>Contact<', '>Kontakt<'),
    ('Apply for a review', 'Ansök om en utvärdering')
]

common_footer = [
    ('We partner with founder-led SaaS companies that digitise public services across Northern Europe.', 'Vi samarbetar med grundarledda SaaS-bolag som digitaliserar offentliga tjänster i norra Europa.'),
    ('Backed by <a', 'Backas upp av <a'),
    ('>Navigate<', '>Navigera<'),
    ('Growth assessment', 'Tillväxtutvärdering'),
    ('>Privacy policy<', '>Integritetspolicy<'),
    ('>Cookie policy<', '>Cookiepolicy<'),
    ('Stay updated', 'Håll dig uppdaterad'),
    ('Get the latest from PubliX Group.', 'Få de senaste nyheterna från PubliX Group.'),
    ('Get the latest from PubliX — acquisitions, insights and founder stories.', 'Få de senaste nyheterna från PubliX – förvärv, insikter och grundarberättelser.'),
    ('Get the latest from PubliX Group', 'Få de senaste nyheterna från PubliX Group'),
    ('your@email.com', 'din@epost.se'),
    ('your@email.se', 'din@epost.se'),
    ('you@company.se', 'du@foretag.se'),
    ('>Subscribe<', '>Prenumerera<'),
    ("Thanks! You\\'re subscribed.", "Tack! Du prenumererar nu."),
    ("Thank you for subscribing!", "Tack för att du prenumererar!"),
    ('Alexander Hübel, CEO', 'Alexander Hübel, vd')
]

common_cookie = [
    ('We use cookies to improve your experience. <a href="https://publixgroup.io/legal/cookie-policy" target="_blank">Read our cookie policy</a>', 'Vi använder cookies för att förbättra din upplevelse. <a href="https://publixgroup.io/legal/cookie-policy" target="_blank">Läs vår cookiepolicy</a>'),
    ('We use cookies to improve your experience. By continuing, you agree to our <a href="https://publixgroup.io/legal/cookie-policy" target="_blank">cookie policy</a>.', 'Vi använder cookies för att förbättra din upplevelse. Genom att fortsätta godkänner du vår <a href="https://publixgroup.io/legal/cookie-policy" target="_blank">cookiepolicy</a>.'),
    ('We use cookies to improve your experience. <a href="https://publixgroup.io/legal/cookie-policy">Read our cookie policy</a>', 'Vi använder cookies för att förbättra din upplevelse. <a href="https://publixgroup.io/legal/cookie-policy">Läs vår cookiepolicy</a>'),
    ('>Accept<', '>Acceptera<'),
    ('>Decline<', '>Avböj<')
]

common_cta = [
    ('Thinking about your next chapter?', 'Funderar du på ditt nästa kapitel?'),
    ("Whether you're exploring your options, curious about where your company stands, or just want to talk to someone who understands your market — we'd welcome the conversation.", "Oavsett om du utforskar dina alternativ, är nyfiken på var ditt bolag står eller bara vill prata med någon som förstår din marknad – välkomnar vi samtalet."),
    ('Discover your growth potential', 'Upptäck din tillväxtpotential'),
    ('Or email Alexander directly', 'Eller mejla Alexander direkt')
]

all_common = common_nav + common_footer + common_cookie + common_cta

replacements_process = [
    ('Redirecting…', 'Omdirigerar…'),
    ('Redirecting to <a href="why-publix.html#process">Why PubliX</a>…', 'Omdirigerar till <a href="why-publix.html#process">Varför PubliX</a>…')
]

replacements_contact = all_common + [
    ('Contact — PubliX Group', 'Kontakt — PubliX Group'),
    ('Get in touch with PubliX Group. Reach Alexander Hübel, CEO, for confidential conversations about your SaaS company. Stockholm office: Kungsgatan 37.', 'Kom i kontakt med PubliX Group. Nå Alexander Hübel, vd, för konfidentiella samtal om ditt SaaS-bolag. Stockholmskontor: Kungsgatan 37.'),
    ('Have something on your mind?', 'Funderar du på något?'),
    ("Let's talk", 'Låt oss prata'),
    ("Whether you're a founder exploring your options or just curious about what we do — every conversation is confidential.", 'Oavsett om du är en grundare som utforskar dina alternativ eller bara är nyfiken på vad vi gör – är varje samtal konfidentiellt.'),
    ('Reach out directly', 'Kontakta oss direkt'),
    ('CEO, PubliX Group', 'vd, PubliX Group'),
    ('General inquiries', 'Allmänna förfrågningar'),
    ('>Office<', '>Kontor<'),
    ('Call Alexander directly', 'Ring Alexander direkt'),
    ('...or send a message', '...eller skicka ett meddelande'),
    ('Thank you!', 'Tack!'),
    ('Your message has been sent. Alexander will get back to you within 2 business days.', 'Ditt meddelande har skickats. Alexander återkommer till dig inom 2 arbetsdagar.'),
    ('>Name<', '>Namn<'),
    ('Your full name', 'Ditt fullständiga namn'),
    ('>Email<', '>E-post<'),
    ('>Company<', '>Företag<'),
    ('Your Company AB', 'Ditt Företag AB'),
    ('>Message<', '>Meddelande<'),
    ('Tell us about your company...', 'Berätta om ditt bolag...'),
    ('Send message ', 'Skicka meddelande '),
    ('Your message goes directly to Alexander. All conversations are confidential.', 'Ditt meddelande går direkt till Alexander. Alla samtal är konfidentiella.'),
    ('We respond within 2 business days', 'Vi svarar inom 2 arbetsdagar'),
    ("Let's talk about the future of public services", 'Låt oss prata om framtiden för offentliga tjänster'),
    ("Whether you're building digital solutions for the public sector or just curious about how we work — we'd love to hear from you.", 'Oavsett om du bygger digitala lösningar för den offentliga sektorn eller bara är nyfiken på hur vi arbetar – hör gärna av dig.'),
    ('Or call Alexander directly:', 'Eller ring Alexander direkt:')
]

replacements_news = all_common + [
    ('News — PubliX Group', 'Nyheter — PubliX Group'),
    ('The latest news from PubliX Group — acquisitions, partnerships and milestones as we build the leading public-sector SaaS platform in the Nordics.', 'De senaste nyheterna från PubliX Group – förvärv, partnerskap och milstolpar när vi bygger den ledande SaaS-plattformen för offentlig sektor i Norden.'),
    ("What's happening at&nbsp;PubliX", 'Vad händer på&nbsp;PubliX'),
    ('Follow our journey as we partner with founder-led SaaS companies across the Nordics — one acquisition at a time.', 'Följ vår resa när vi samarbetar med grundarledda SaaS-bolag i hela Norden – ett förvärv i taget.'),
    ('>All<', '>Alla<'),
    ('>Acquisitions<', '>Förvärv<'),
    ('>Appointments<', '>Utnämningar<'),
    ('>Appointment<', '>Utnämning<'),
    ('>Acquisition<', '>Förvärv<'),
    ('PubliX Group appoints Alexander Hübel as CEO', 'PubliX Group utser Alexander Hübel till vd'),
    ('Alexander Hübel has been appointed Group CEO of PubliX Group, bringing extensive experience in scaling technology companies and building platforms in the Nordic market.', 'Alexander Hübel har utsetts till koncernchef för PubliX Group och tar med sig omfattande erfarenhet av att skala teknikbolag och bygga plattformar på den nordiska marknaden.'),
    ('Read more ', 'Läs mer '),
    ('PubliX Group partners with Embrace Safety', 'PubliX Group ingår partnerskap med Embrace Safety'),
    ('A powerful SaaS platform enabling knowledge-based crime prevention and safety promotion for municipalities and local authorities.', 'En kraftfull SaaS-plattform som möjliggör kunskapsbaserad brottsprevention och trygghetsfrämjande arbete för kommuner och lokala myndigheter.'),
    ('PubliX Group partners with Koivu Solutions (Sotender)', 'PubliX Group ingår partnerskap med Koivu Solutions (Sotender)'),
    ('A modern SaaS solution for connecting healthcare workers with open shifts, increasing reach and reducing costs for healthcare providers.', 'En modern SaaS-lösning för att koppla samman vårdpersonal med lediga pass, vilket ökar räckvidden och minskar kostnaderna för vårdgivare.'),
    ('PubliX Group enters Finland through partnership with Aspicore', 'PubliX Group etablerar sig i Finland genom partnerskap med Aspicore'),
    ("A full-service software provider within grant management, marking PubliX Group's expansion into the Finnish market.", 'En fullserviceleverantör av mjukvara för stiftelsehantering, vilket markerar PubliX Groups expansion in på den finska marknaden.'),
    ('PubliX Group partners with digiPlant', 'PubliX Group ingår partnerskap med digiPlant'),
    ("A market leader within application management systems for foundations, strengthening PubliX's position in the grant management vertical.", 'En marknadsledare inom ansökningssystem för stiftelser, vilket stärker PubliX position inom stiftelsehanteringsvertikalen.'),
    ('PubliX Group welcomes Tidvis', 'PubliX Group välkomnar Tidvis'),
    ('Strengthening digital care solutions in the Nordics — Tidvis develops platforms for social services, helping municipalities manage case work and compliance.', 'Stärker digitala omsorgslösningar i Norden — Tidvis utvecklar plattformar för socialtjänsten och hjälper kommuner att hantera ärenden och regelefterlevnad.'),
    ('April 14, 2026', '14 april 2026'),
    ('February 23, 2026', '23 februari 2026'),
    ('September 2, 2025', '2 september 2025'),
    ('August 25, 2025', '25 augusti 2025')
]

replacements_career = all_common + [
    ('Our Team — PubliX Group', 'Vårt team — PubliX Group'),
    ('Meet the team behind PubliX Group — the operators, founders and board members building the growth platform for SaaS companies in public services.', 'Träffa teamet bakom PubliX Group — operatörerna, grundarna och styrelsemedlemmarna som bygger tillväxtplattformen för SaaS-bolag inom offentlig sektor.'),
    ('> Our team<', '> Vårt team<'),
    ('The people behind PubliX', 'Människorna bakom PubliX'),
    ('PubliX is built by operators who have founded, scaled and run software companies. When you talk to us, you talk to someone who understands your world.', 'PubliX är byggt av operatörer som har grundat, skalat och drivit mjukvarubolag. När du pratar med oss pratar du med någon som förstår din värld.'),
    ('Management team', 'Ledningsgrupp'),
    ("Alexander has spent over 15 years building and scaling software companies. Before founding PubliX Group, he held leadership roles across SaaS, digital transformation, and M&amp;A. He leads the group's strategy, acquisitions, and founder relationships.", 'Alexander har tillbringat över 15 år med att bygga och skala mjukvarubolag. Innan han grundade PubliX Group hade han ledande roller inom SaaS, digital transformation och M&amp;A. Han leder gruppens strategi, förvärv och grundarrelationer.'),
    ('>Group CEO<', '>Koncernchef (CEO)<'),
    ('Marcus brings deep experience in M&amp;A and corporate finance, with a focus on technology companies. He leads the deal process from first conversation to close, ensuring every transaction is structured fairly and transparently.', 'Marcus har djup erfarenhet inom M&amp;A och corporate finance, med fokus på teknikbolag. Han leder affärsprocessen från första samtalet till avslut, och säkerställer att varje transaktion struktureras rättvist och transparent.'),
    ('Head of M&amp;A', 'M&amp;A-chef'),
    ("Erik oversees the group's financial operations and reporting. With a background in finance and operations across technology companies, he ensures our portfolio companies have the financial infrastructure to scale.", 'Erik övervakar gruppens finansiella verksamhet och rapportering. Med bakgrund inom finans och drift i teknikbolag säkerställer han att våra portföljbolag har den finansiella infrastrukturen för att skala.'),
    ('VP Finance &amp; Operations', 'VP Finans &amp; Drift'),
    ("Patrick leads the technical strategy across the group, including AI capabilities, shared infrastructure, and software architecture. He works hands-on with every portfolio company's development team.", "Patrick leder den tekniska strategin över hela gruppen, inklusive AI-kapacitet, delad infrastruktur och mjukvaruarkitektur. Han arbetar praktiskt med varje portföljbolags utvecklingsteam."),
    ('>CTO<', '>Teknisk chef (CTO)<'),
    ('Board of Directors', 'Styrelse'),
    ('Patrik is an experienced technology executive and board professional. As Chairman of the Board, he provides strategic guidance and governance oversight to the group.', 'Patrik är en erfaren teknikchef och styrelseproffs. Som styrelseordförande ger han strategisk vägledning och tillsyn över styrningen av gruppen.'),
    ('Chairman of the Board', 'Styrelseordförande'),
    ("Viktor brings investment and technology expertise to the board as an independent external director. He contributes to PubliX's strategic direction and portfolio company development.", 'Viktor tillför investerings- och teknikexpertis till styrelsen som en oberoende extern ledamot. Han bidrar till PubliX strategiska riktning och portföljbolagens utveckling.'),
    ('Board member, External', 'Styrelseledamot, Extern'),
    ('Anders represents Aspira Partners on the PubliX Group board. He brings deep experience in building and scaling Nordic technology companies.', 'Anders representerar Aspira Partners i PubliX Groups styrelse. Han bidrar med djup erfarenhet av att bygga och skala nordiska teknikbolag.'),
    ('Board member, Aspira Partners', 'Styrelseledamot, Aspira Partners'),
    ("Anton represents Aspira Partners on the PubliX Group board. He contributes investment expertise and supports the group's acquisition and growth strategy.", 'Anton representerar Aspira Partners i PubliX Groups styrelse. Han bidrar med investeringsexpertis och stöder gruppens förvärvs- och tillväxtstrategi.'),
    ('Janne co-founded Koivu Solutions and serves on the PubliX Group board as an entrepreneur representative. He brings firsthand experience in scaling Finnish healthcare technology into new Nordic markets.', 'Janne var med och grundade Koivu Solutions och sitter i PubliX Groups styrelse som entreprenörsrepresentant. Han bidrar med förstahandserfarenhet av att skala finsk sjukvårdsteknik till nya nordiska marknader.'),
    ('Board member, Entrepreneur', 'Styrelseledamot, Entreprenör'),
    ('Alexander co-founded digiPlant and serves on the PubliX Group board as an entrepreneur representative. He brings hands-on SaaS founder experience and deep knowledge of public procurement technology.', 'Alexander var med och grundade digiPlant och sitter i PubliX Groups styrelse som entreprenörsrepresentant. Han bidrar med praktisk erfarenhet som SaaS-grundare och djup kunskap om offentlig upphandlingsteknik.'),
    ('Company leaders', 'Bolagsledare'),
    ('The founders who run our portfolio companies.', 'Grundarna som driver våra portföljbolag.'),
    ("Mattias founded Tidvis to transform how Swedish municipalities handle social care. His deep understanding of social workers' daily reality drives the platform's design and development.", 'Mattias grundade Tidvis för att förändra hur svenska kommuner hanterar socialtjänsten. Hans djupa förståelse för socialsekreterares dagliga verklighet driver plattformens design och utveckling.'),
    ('Founder &amp; CEO, Tidvis', 'Grundare &amp; vd, Tidvis'),
    ('Alexander co-founded digiPlant to modernise public procurement. Since joining PubliX, his team has launched two new AI-powered products and undergone a complete AI upskilling programme.', 'Alexander var med och grundade digiPlant för att modernisera offentlig upphandling. Sedan de anslöt sig till PubliX har hans team lanserat två nya AI-drivna produkter och genomgått ett komplett AI-utbildningsprogram.'),
    ('Co-Founder &amp; CEO, digiPlant', 'Medgrundare &amp; vd, digiPlant'),
    ("Juha co-founded Aspicore and built it into Finland's leading foundation management platform over more than a decade. He now supports the company's continued growth as founder.", 'Juha var med och grundade Aspicore och byggde det till Finlands ledande plattform för stiftelsehantering under mer än ett decennium. Han stöder nu bolagets fortsatta tillväxt som grundare.'),
    ('Co-Founder &amp; CEO, Aspicore', 'Medgrundare &amp; vd, Aspicore'),
    ('Janne co-founded Koivu Solutions and built Sotender, a procurement platform for Finnish healthcare. With PubliX, he expanded into Sweden within months and is now planning the next market.', 'Janne var med och grundade Koivu Solutions och byggde Sotender, en upphandlingsplattform för finsk sjukvård. Med PubliX expanderade han till Sverige på några månader och planerar nu för nästa marknad.'),
    ('Co-Founder &amp; CEO, Koivu Solutions', 'Medgrundare &amp; vd, Koivu Solutions'),
    ('Johan leads Embrace Safety, helping public organisations and enterprises manage workplace safety and compliance through a modern digital platform.', 'Johan leder Embrace Safety och hjälper offentliga organisationer och företag att hantera arbetsplatssäkerhet och regelefterlevnad genom en modern digital plattform.'),
    ('CEO, Embrace Safety', 'vd, Embrace Safety'),
    ('>Open positions<', '>Lediga tjänster<'),
    ('>Join us<', '>Bli en av oss<'),
    ('View all open positions', 'Se alla lediga tjänster'),
    ("We're always looking for talented people who want to build software that matters.", 'Vi letar alltid efter begåvade människor som vill bygga mjukvara som gör skillnad.'),
    ('Browse jobs on Teamtailor', 'Se jobb på Teamtailor'),
    ('Careers at our companies', 'Karriärer hos våra bolag'),
    ('Or join one of our portfolio companies', 'Eller gå med i ett av våra portföljbolag'),
    ('Each company runs its own hiring. Reach out directly to learn about opportunities.', 'Varje bolag sköter sin egen rekrytering. Hör av dig direkt för att få veta mer om möjligheterna.'),
    ('Social care software', 'Mjukvara för socialomsorg'),
    ('Visit website ', 'Besök hemsida '),
    ('Public procurement', 'Offentlig upphandling'),
    ('Foundation management', 'Stiftelsehantering'),
    ('Healthcare procurement', 'Sjukvårdsupphandling'),
    ('Safety &amp; compliance', 'Säkerhet &amp; regelefterlevnad')
]

replacements_companies = all_common + [
    ('Our Companies — PubliX Group Portfolio', 'Våra bolag — PubliX Group Portfölj'),
    ('Meet the five founder-led SaaS companies in the PubliX Group portfolio — building mission-critical software for Nordic public services in social care, procurement, safety and more.', 'Möt de fem grundarledda SaaS-bolagen i PubliX Groups portfölj – som bygger affärskritisk mjukvara för nordiska offentliga tjänster inom socialomsorg, upphandling, säkerhet med mera.'),
    ('> Our companies<', '> Våra bolag<'),
    ('Founder-led, mission&#8209;driven', 'Grundarledda, uppdragsdrivna'),
    ('Every company in the PubliX portfolio was built by founders who care deeply about public services. They chose to join us — and stayed to keep building.', 'Varje bolag i PubliX portfölj byggdes av grundare som bryr sig djupt om offentliga tjänster. De valde att ansluta sig till oss – och stannade för att fortsätta bygga.'),
    ('>Social care<', '>Socialomsorg<'),
    ('Tidvis develops digital platforms for social services, helping municipalities manage case work, documentation, and compliance more efficiently. Their tools are designed by people who understand the daily reality of social workers.', 'Tidvis utvecklar digitala plattformar för socialtjänsten och hjälper kommuner att hantera ärenden, dokumentation och regelefterlevnad mer effektivt. Deras verktyg är designade av personer som förstår socialsekreterares dagliga verklighet.'),
    ('>Founder<', '>Grundare<'),
    ('>CEO<', '>vd<'),
    ('Public procurement', 'Offentlig upphandling'),
    ('digiPlant automates and streamlines public procurement for municipalities and government agencies. Their platform reduces administrative burden and improves compliance in purchasing processes.', 'digiPlant automatiserar och effektiviserar offentlig upphandling för kommuner och statliga myndigheter. Deras plattform minskar den administrativa bördan och förbättrar regelefterlevnaden i inköpsprocesser.'),
    ('Co-Founder &amp; CEO', 'Medgrundare &amp; vd'),
    ('Foundation management', 'Stiftelsehantering'),
    ('Aspicore builds digital platforms for foundation and grant management, helping public-benefit organisations process applications, manage grants and ensure transparent governance.', 'Aspicore bygger digitala plattformar för stiftelse- och bidragshantering, och hjälper allmännyttiga organisationer att hantera ansökningar, administrera bidrag och säkerställa transparent styrning.'),
    ('Healthcare procurement', 'Sjukvårdsupphandling'),
    ('Koivu Solutions, through its Sotender platform, digitises procurement processes for healthcare organisations in Finland — helping hospitals and care providers find the right suppliers efficiently and compliantly.', 'Koivu Solutions digitaliserar genom sin Sotender-plattform upphandlingsprocesser för vårdorganisationer i Finland – vilket hjälper sjukhus och vårdgivare att hitta rätt leverantörer effektivt och i enlighet med regelverken.'),
    ('Safety &amp; compliance', 'Säkerhet &amp; regelefterlevnad'),
    ('Embrace Safety helps public organisations and enterprises manage workplace safety, incident reporting, and regulatory compliance through a modern digital platform.', 'Embrace Safety hjälper offentliga organisationer och företag att hantera arbetsplatssäkerhet, incidentrapportering och regelefterlevnad genom en modern digital plattform.'),
    ('CEO &amp; Head of Sales', 'vd &amp; Säljchef'),
    ('"PubliX helped us think much bigger and set a far more ambitious market strategy. By training our team in how to use AI, they\'ve helped us reach our goals much faster than we thought was possible."', '"PubliX hjälpte oss att tänka mycket större och sätta en mycket mer ambitiös marknadsstrategi. Genom att utbilda vårt team i hur man använder AI har de hjälpt oss att nå våra mål mycket snabbare än vi trodde var möjligt."'),
    ('Post-acquisition', 'Efter förvärvet'),
    ('What happens after you join', 'Vad händer när du har anslutit'),
    ("Joining PubliX is designed to be seamless. Here's what the first year looks like for a typical portfolio company.", 'Att ansluta till PubliX är utformat för att vara smidigt. Så här ser det första året ut för ett typiskt portföljbolag.'),
    ('Day one: Nothing changes', 'Dag ett: Inget förändras'),
    ("Your team, your office, your customers. We're not here to reorganise.", 'Ditt team, ditt kontor, dina kunder. Vi är inte här för att omorganisera.'),
    ('Months 1–3: Foundations', 'Månad 1–3: Grunderna'),
    ('We work together on economics, pricing, compliance and security.', 'Vi arbetar tillsammans med ekonomi, prissättning, regelefterlevnad och säkerhet.'),
    ('Months 3–12: Growth', 'Månad 3–12: Tillväxt'),
    ('Cross-sell to shared customers, open new countries, add adjacent workflows.', 'Korsförsäljning till gemensamma kunder, öppna nya länder, lägga till angränsande arbetsflöden.'),
    ('Year 1+: Platform value', 'År 1+: Plattformsvärde'),
    ('Share in the collective growth of the group. Your success compounds.', 'Ta del av gruppens gemensamma tillväxt. Din framgång ger ränta på ränta.')
]

replacements_about = all_common + [
    ('About PubliX Group — Operators building for the public good', 'Om PubliX Group — Operatörer som bygger för samhällsnyttan'),
    ('Learn how PubliX Group works with founder-led SaaS companies serving the Nordic public sector. Our thesis, value creation model, and the team behind the platform.', 'Läs om hur PubliX Group arbetar med grundarledda SaaS-bolag som levererar till den nordiska offentliga sektorn. Vår tes, värdeskapande modell och teamet bakom plattformen.'),
    ('> About PubliX Group<', '> Om PubliX Group<'),
    ('Operators building for the public&nbsp;good', 'Operatörer som bygger för samhälls&nbsp;nyttan'),
    ("PubliX Group unites founder-led SaaS companies that digitise public services across Northern Europe. We're operators — not financial engineers. Every decision we make starts with one question: does this help our companies build better products?", "PubliX Group förenar grundarledda SaaS-bolag som digitaliserar offentliga tjänster i norra Europa. Vi är operatörer – inte finansiella ingenjörer. Varje beslut vi fattar börjar med en fråga: hjälper detta våra bolag att bygga bättre produkter?"),
    ('>Our thesis<', '>Vår tes<'),
    ('Public-sector software is its own discipline', 'Mjukvara för offentlig sektor är en egen disciplin'),
    ('Public sector means procurement rules, framework agreements, long sales cycles and regulated buyers. It requires patience, domain expertise and a deep understanding of how the public sector actually buys technology.', 'Offentlig sektor innebär upphandlingsregler, ramavtal, långa säljcykler och reglerade köpare. Det kräver tålamod, domänexpertis och en djup förståelse för hur den offentliga sektorn faktiskt köper teknik.'),
    ('PubliX concentrates in this one vertical', 'PubliX koncentrerar sig på denna enda vertikal'),
    (' — and intends to be the best in the Nordics. When a founder joins PubliX, they get a parent company that truly understands their market.', ' – och har för avsikt att bli bäst i Norden. När en grundare ansluter sig till PubliX får de ett moderbolag som verkligen förstår deras marknad.'),
    ('We grow through ', 'Vi växer genom '),
    ('shared customers, not cost-cutting', 'gemensamma kunder, inte kostnadsbesparingar'),
    ('. Our companies sell to the same and adjacent customers — municipalities, regions, foundations, public agencies. Cross-selling and collaboration between portfolio companies grows revenue organically, rather than stripping cost or merging teams. Every company keeps its identity, its team and its autonomy.', '. Våra bolag säljer till samma och angränsande kunder – kommuner, regioner, stiftelser, statliga myndigheter. Korsförsäljning och samarbete mellan portföljbolag ökar intäkterna organiskt, i stället för att dra ner på kostnader eller slå ihop team. Varje bolag behåller sin identitet, sitt team och sin autonomi.'),
    ('>One vertical<', '>En vertikal<'),
    ('100% focus on public-sector SaaS across the Nordics', '100 % fokus på SaaS för offentlig sektor i hela Norden'),
    ('>Shared customers<', '>Gemensamma kunder<'),
    ('Municipalities, regions &amp; foundations that buy from multiple companies', 'Kommuner, regioner &amp; stiftelser som köper från flera bolag'),
    ('>Founder-led<', '>Grundarledda<'),
    ('Every company keeps its CEO, team &amp; decision-making authority', 'Varje bolag behåller sin vd, sitt team &amp; sin beslutanderätt'),
    ('>Growth, not cuts<', '>Tillväxt, inte nedskärningar<'),
    ('We grow revenue through cross-sell — not cost synergies', 'Vi ökar intäkterna genom korsförsäljning – inte kostnadssynergier'),
    ('>How we create value<', '>Hur vi skapar värde<'),
    ('Two tracks. One goal: make your company stronger.', 'Två spår. Ett mål: att göra ditt bolag starkare.'),
    ('Every company we work with benefits from two parallel value creation tracks — one focused on strengthening your foundation, the other on accelerating growth.', 'Varje bolag vi arbetar med drar nytta av två parallella värdeskapande spår – ett med fokus på att stärka er grund, det andra på att accelerera tillväxten.'),
    ('>Foundations<', '>Grunderna<'),
    ('Strengthen the operational core so you can scale with confidence.', 'Stärk den operativa kärnan så att ni kan skala med tillförsikt.'),
    ('Clean economics — clear reporting, margins and unit economics', 'Tydlig ekonomi – tydlig rapportering, marginaler och enhetsekonomi'),
    ("Sensible pricing — value-based models that capture what you're worth", 'Förnuftig prissättning – värdebaserade modeller som fångar ert värde'),
    ('Commercial discipline — pipeline management and sales processes', 'Kommersiell disciplin – pipeline-hantering och säljprocesser'),
    ('Security &amp; compliance uplift — ISO 27001, GDPR, public-sector standards', 'Säkerhet &amp; regelefterlevnad – ISO 27001, GDPR, standarder för offentlig sektor'),
    ('AI &amp; engineering capability — embedded tech expertise, not consultants', 'AI &amp; teknisk förmåga – inbyggd teknisk expertis, inte konsulter'),
    ('>Growth<', '>Tillväxt<'),
    ('Expand your market reach through the power of the platform.', 'Utöka er marknadsräckvidd genom kraften i plattformen.'),
    ('Sell more to shared customers — cross-sell across the portfolio', 'Sälj mer till gemensamma kunder – korsförsäljning över hela portföljen'),
    ('Open new Nordic countries for proven products', 'Öppna nya nordiska länder för beprövade produkter'),
    ('Add adjacent workflows for the same buyer persona', 'Lägg till angränsande arbetsflöden för samma köparpersona'),
    ('Joint marketing &amp; events to shared decision-makers', 'Gemensam marknadsföring &amp; evenemang mot gemensamma beslutsfattare'),
    ('Warm introductions through trusted existing relationships', 'Varma introduktioner genom pålitliga befintliga relationer'),
    ('"Founders typically reinvest part of their proceeds into the group, sharing in the value of the whole platform rather than just selling and leaving."', '"Grundare återinvesterar vanligtvis en del av sina intäkter i gruppen och tar del av värdet i hela plattformen i stället för att bara sälja och lämna."'),
    ('— This is by design. When founders stay invested, incentives stay aligned.', '— Detta är avsiktligt. När grundare förblir investerade förblir incitamenten i linje.'),
    ('>How we work with AI<', '>Hur vi arbetar med AI<'),
    ('AI is how we create value:<br>Every product, every workflow, every job role', 'AI är hur vi skapar värde:<br>Varje produkt, varje arbetsflöde, varje yrkesroll'),
    ("We don't just talk about AI — we embed it across every company in the group. From new product capabilities to automating internal operations, AI is central to how PubliX creates value.", "Vi pratar inte bara om AI – vi integrerar det i varje bolag i gruppen. Från nya produktfunktioner till automatisering av intern verksamhet, är AI centralt för hur PubliX skapar värde."),
    ('>Product AI<', '>Produkt-AI<'),
    ('We help our companies build AI-powered features into their products — from intelligent automation to predictive analytics for public-sector workflows.', 'Vi hjälper våra bolag att bygga in AI-drivna funktioner i sina produkter – från intelligent automatisering till prediktiv analys för offentliga sektorns arbetsflöden.'),
    ('>Operational AI<', '>Operativ AI<'),
    ('We automate lead generation, lead nurture, customer support, software development and financial and administrative workflows across the group — so our companies can focus on building great products instead of admin.', 'Vi automatiserar leadgenerering, kundvård, kundsupport, mjukvaruutveckling samt finansiella och administrativa arbetsflöden över hela gruppen – så att våra bolag kan fokusera på att bygga fantastiska produkter istället för administration.'),
    ('>AI upskilling<', '>AI-kompetensutveckling<'),
    ('We train every team across the group to use AI tools effectively — turning capability into results. Our companies reach their goals faster than they thought possible.', 'Vi utbildar varje team i gruppen i att använda AI-verktyg effektivt – och förvandlar förmåga till resultat. Våra bolag når sina mål snabbare än de trodde var möjligt.')
]

replacements_index = replacements_career + replacements_companies + replacements_about + all_common + [
    ('PubliX Group — For founders of Nordic public-sector SaaS', 'PubliX Group — För grundare av nordiska SaaS-bolag inom offentlig sektor'),
    ('PubliX Group is the growth platform for SaaS founders in public services. We help you scale through shared customers, AI capabilities, and expansion into new markets. Discover your growth potential.', 'PubliX Group är tillväxtplattformen för SaaS-grundare inom offentlig sektor. Vi hjälper dig att skala genom gemensamma kunder, AI-förmågor och expansion till nya marknader. Upptäck din tillväxtpotential.'),
    ("What's holding your company back from its next level?", 'Vad hindrar ditt bolag från att nå nästa nivå?'),
    ('The growth platform for <em>SaaS founders in public services</em>', 'Tillväxtplattformen för <em>SaaS-grundare inom offentliga tjänster</em>'),
    ("We partner with founders who've built great software for the public sector — and help them break through the barriers that limit growth. Whether it's a local market, technical debt, lack of AI capability, or simply building alone — PubliX gives you the resources, the network, and the community to scale.", 'Vi samarbetar med grundare som har byggt fantastisk mjukvara för den offentliga sektorn – och hjälper dem att bryta igenom barriärerna som begränsar tillväxten. Oavsett om det är en lokal marknad, teknisk skuld, brist på AI-förmåga eller att man helt enkelt bygger ensam – PubliX ger dig resurserna, nätverket och gemenskapen för att skala.'),
    ('Confidential · No obligation · Founder to founder', 'Konfidentiellt · Inga förpliktelser · Från grundare till grundare'),
    ('Why founders choose PubliX', 'Varför grundare väljer PubliX'),
    ('5 founder-led companies already in the group', '5 grundarledda bolag redan i gruppen'),
    ('Swedish municipalities as customers', 'Svenska kommuner som kunder'),
    ('Finnish wellbeing services counties', 'Finska välfärdsområden'),
    ('Portfolio companies', 'Portföljbolag'),
    ('Annual revenue', 'Årlig omsättning'),
    ('Employees across the group', 'Anställda i gruppen'),
    ('Struggling with long sales cycles?', 'Kämpar du med långa säljcykler?'),
    ('Your customers are already our customers', 'Dina kunder är redan våra kunder'),
    ('When companies serving the same public-sector clients join the same group, something powerful happens: <strong>cross-selling becomes natural</strong>. Your scheduling platform is already deployed in the municipality that needs our grants management system.', 'När bolag som levererar till samma offentliga kunder ansluter till samma grupp, händer något kraftfullt: <strong>korsförsäljning blir naturligt</strong>. Din schemaläggningsplattform används redan i den kommun som behöver vårt bidragshanteringssystem.'),
    ('Instead of competing for attention, our portfolio companies <strong>open doors for each other</strong> — shared customer relationships, joint marketing resources, and warm introductions that would take years to build alone.', 'Istället för att konkurrera om uppmärksamhet, <strong>öppnar våra portföljbolag dörrar för varandra</strong> – gemensamma kundrelationer, delade marknadsföringsresurser och varma introduktioner som skulle ta år att bygga upp ensam.'),
    ('Shared relationships', 'Gemensamma relationer'),
    ('Your products reach new customers through existing, trusted relationships in the group.', 'Dina produkter når nya kunder genom befintliga, pålitliga relationer i gruppen.'),
    ('Joint marketing', 'Gemensam marknadsföring'),
    ('Pool resources for events, campaigns and content aimed at the same decision-makers.', 'Dela resurser för evenemang, kampanjer och innehåll riktat till samma beslutsfattare.'),
    ('Revenue uplift', 'Intäktsökning'),
    ('Cross-selling across the portfolio drives organic top-line growth for every company.', 'Korsförsäljning i portföljen driver organisk omsättningstillväxt för varje bolag.'),
    ('Skip the cold outreach — get introduced by a colleague the customer already trusts.', 'Hoppa över kall försäljning – bli introducerad av en kollega som kunden redan litar på.'),
    ('Losing tenders you should be winning?', 'Förlorar du upphandlingar du borde vinna?'),
    ("We've run more public procurements than anyone", 'Vi har genomfört fler offentliga upphandlingar än de flesta'),
    ('Public procurement is complex, bureaucratic and unforgiving. Miss a requirement, lose the deal. For a single company, each tender is a costly bet.', 'Offentlig upphandling är komplext, byråkratiskt och oförlåtande. Missar du ett krav förlorar du affären. För ett enskilt bolag är varje upphandling en kostsam satsning.'),
    ('With multiple portfolio companies, PubliX runs <strong>more public tenders, across more municipalities, more often</strong> than any individual company could. That volume gives us a <strong>structural advantage</strong> — we know the process, we know the pitfalls, and we have dedicated resources to help you win.', 'Med flera portföljbolag genomför PubliX <strong>fler offentliga upphandlingar, i fler kommuner, oftare</strong> än något enskilt bolag skulle kunna. Den volymen ger oss en <strong>strukturell fördel</strong> – vi känner till processen, fallgropen och vi har dedikerade resurser för att hjälpa dig att vinna.'),
    ('Plus shared IT infrastructure, security auditing and compliance frameworks that meet the toughest public-sector standards.', 'Plus delad IT-infrastruktur, säkerhetsgranskning och regelverk för regelefterlevnad som möter de tuffaste standarderna inom offentlig sektor.'),
    ('Dedicated procurement specialists across the group', 'Dedikerade upphandlingsspecialister i gruppen'),
    ('Shared compliance and IT security frameworks', 'Delade ramverk för regelefterlevnad och IT-säkerhet'),
    ('Volume advantage: more tenders, more municipalities, more wins', 'Volymfördel: fler upphandlingar, fler kommuner, fler vinster'),
    ('Template library from hundreds of successful bids', 'Mallbibliotek från hundratals framgångsrika anbud'),
    ('Legal review and risk assessment for every submission', 'Juridisk granskning och riskbedömning för varje inlämning'),
    ('Worried about losing control of your company?', 'Orolig för att förlora kontrollen över ditt bolag?'),
    ("We don't change what works. We build on it.", 'Vi ändrar inte på det som fungerar. Vi bygger vidare på det.'),
    ("When we acquire a company, we're not buying a product — we're investing in <strong>the people and organisation that built it</strong>. That value doesn't survive aggressive restructuring.", 'När vi förvärvar ett bolag köper vi inte en produkt – vi investerar i <strong>människorna och organisationen som byggde den</strong>. Det värdet överlever inte aggressiva omstruktureringar.'),
    ('Every company in our group <strong>keeps its own CEO, its own team, its own office, and its own decision-making authority</strong>. We don\'t centralise functions to cut costs. We don\'t merge brands.', 'Varje bolag i vår grupp <strong>behåller sin egen vd, sitt eget team, sitt eget kontor och sin egen beslutanderätt</strong>. Vi centraliserar inte funktioner för att skära kostnader. Vi slår inte ihop varumärken.'),
    ('Instead, we invest in developing that existing value — through shared learning, cross-company competence building, and the kind of strategic support that helps founders focus on what they do best: building great products.', 'I stället investerar vi i att utveckla det befintliga värdet – genom gemensamt lärande, kompetensutveckling över bolagsgränserna och det strategiska stöd som hjälper grundare att fokusera på det de gör bäst: att bygga fantastiska produkter.'),
    ('<strong>Your CEO stays.</strong> Full decision-making authority retained.', '<strong>Din vd stannar.</strong> Full beslutanderätt bibehålls.'),
    ('<strong>Your team stays.</strong> No layoffs, no "efficiency" programmes.', '<strong>Ditt team stannar.</strong> Inga uppsägningar, inga "effektiviseringsprogram".'),
    ('<strong>Your office stays.</strong> You operate from where you are.', '<strong>Ditt kontor stannar.</strong> Du driver verksamheten där du är.'),
    ('<strong>Your brand stays.</strong> Your identity is part of your value.', '<strong>Ditt varumärke stannar.</strong> Din identitet är en del av ditt värde.'),
    ('<strong>Your culture stays.</strong> We add resources, not restrictions.', '<strong>Din kultur stannar.</strong> Vi tillför resurser, inte restriktioner.'),
    ('"We joined PubliX to grow faster — and the first thing they told us was \'keep doing what you\'re doing, we\'re here to help.\'"', '"Vi anslöt oss till PubliX för att växa snabbare – och det första de sa till oss var \'fortsätt med det ni gör, vi är här för att hjälpa till.\'"'),
    ('Is AI making your product obsolete?', 'Gör AI din produkt föråldrad?'),
    ('Embedded AI capability from day one', 'Inbyggd AI-kapacitet från dag ett'),
    ('If you\'ve built a successful SaaS company over the past 10 or 20 years, you already know: <strong>AI will fundamentally change the competitive landscape</strong>. New products, new pricing, new expectations.', 'Om du har byggt ett framgångsrikt SaaS-bolag under de senaste 10 eller 20 åren vet du redan: <strong>AI kommer att förändra det konkurrenskraftiga landskapet i grunden</strong>. Nya produkter, ny prissättning, nya förväntningar.'),
    ('PubliX gives you access to <strong>dedicated AI and technology expertise</strong> — not as a consultant engagement, but as an embedded capability. We help you modernise your tech stack, automate internal processes, build AI-powered features, and develop new go-to-market strategies.', 'PubliX ger dig tillgång till <strong>dedikerad AI- och teknikexpertis</strong> – inte som en konsultinsats, utan som en integrerad kapacitet. Vi hjälper dig att modernisera din teknikstack, automatisera interna processer, bygga AI-drivna funktioner och utveckla nya go-to-market-strategier.'),
    ('The companies that adapt fastest will win. <strong>We want you on that journey with us.</strong>', 'Bolagen som anpassar sig snabbast vinner. <strong>Vi vill ha dig med på den resan.</strong>'),
    ('AI product features', 'AI-produktfunktioner'),
    ('Integrate AI into your product to deliver more value and differentiate from competitors.', 'Integrera AI i din produkt för att leverera mer värde och differentiera dig från konkurrenter.'),
    ('Sales automation', 'Försäljningsautomatisering'),
    ('AI-driven lead generation, qualification and outreach to accelerate your pipeline.', 'AI-driven leadgenerering, kvalificering och bearbetning för att snabba upp din pipeline.'),
    ('Process modernisation', 'Processmodernisering'),
    ('Automate internal workflows — support, onboarding, billing — to free up your team.', 'Automatisera interna arbetsflöden – support, onboarding, fakturering – för att frigöra tid för ditt team.'),
    ('Data-driven strategy', 'Datadriven strategi'),
    ('Market intelligence, pricing optimisation and competitive analysis powered by AI.', 'Marknadsanalys, prisoptimering och konkurrentanalys driven av AI.'),
    ('Ready to grow beyond your home market?', 'Redo att växa utanför din hemmamarknad?'),
    ('Take your product beyond the Nordics', 'Ta din produkt utanför Norden'),
    ('Your product works in your home market. It could work across Europe. But international expansion requires <strong>market knowledge, legal expertise, and localisation capabilities</strong> that are hard to build from scratch.', 'Din produkt fungerar på din hemmamarknad. Den kan fungera i hela Europa. Men internationell expansion kräver <strong>marknadskännedom, juridisk expertis och lokaliseringskapacitet</strong> som är svår att bygga upp från grunden.'),
    ('PubliX already has <strong>pan-Nordic presence</strong> and is currently expanding into Northern Europe, the British and the DACH region. We bring market intelligence, legal frameworks, language capabilities and marketing expertise that make it possible for our companies to launch in new markets.', 'PubliX har redan <strong>paneuropeisk närvaro</strong> och expanderar för närvarande i norra Europa, Storbritannien och DACH-regionen. Vi tillför marknadskunskap, juridiska ramverk, språkkunskaper och marknadsföringsexpertis som gör det möjligt för våra bolag att lansera på nya marknader.'),
    ('The European public sector is a massive, under-digitised market. We help you get there.', 'Den europeiska offentliga sektorn är en massiv, underdigitaliserad marknad. Vi hjälper dig att nå dit.'),
    ('Active operations in Sweden and Finland today', 'Aktiv verksamhet i Sverige och Finland i dag'),
    ('Market intelligence and regulatory mapping for European expansion', 'Marknadsanalys och kartläggning av regelverk för europeisk expansion'),
    ('Legal expertise for new jurisdictions and public procurement', 'Juridisk expertis för nya jurisdiktioner och offentlig upphandling'),
    ('Localisation — language, marketing and cultural adaptation', 'Lokalisering – språk, marknadsföring och kulturell anpassning'),
    ('International investor network through Aspira Partners', 'Internationellt investerarnätverk genom Aspira Partners'),
    ('They made the move', 'De tog steget'),
    ('Who we are', 'Vilka vi är'),
    ('Operators, not financiers', 'Operatörer, inte finansiärer'),
    ("PubliX is led by people who have built, scaled and operated software companies. When you talk to us, you talk to someone who has done the job you're doing.", "PubliX leds av personer som har byggt, skalat och drivit mjukvarubolag. När du pratar med oss, pratar du med någon som har gjort det jobb du gör."),
    ('By application · Confidential', 'Via ansökan · Konfidentiellt'),
    ('We offer a select number of founders a confidential, in-depth growth assessment — a serious analysis of how your company could scale with the right resources. More markets, stronger products, AI capabilities, reduced technical debt. This isn\'t a generic report. It\'s a bespoke process, delivered personally by our CEO.', 'Vi erbjuder ett utvalt antal grundare en konfidentiell, djupgående tillväxtutvärdering – en seriös analys av hur ditt bolag skulle kunna skala med rätt resurser. Fler marknader, starkare produkter, AI-förmågor, minskad teknisk skuld. Detta är inte en generisk rapport. Det är en skräddarsydd process, levererad personligen av vår vd.'),
    ('You apply', 'Du ansöker'),
    ('Tell us who you are and what your company does. We review every application personally.', 'Berätta vem du är och vad ditt bolag gör. Vi granskar varje ansökan personligen.'),
    ('We confirm fit &amp; sign NDA', 'Vi bekräftar passning &amp; skriver NDA'),
    ('If there\'s a potential fit, we set up a confidential conversation and sign a mutual NDA to protect both sides.', 'Om det finns en potentiell matchning sätter vi upp ett konfidentiellt samtal och tecknar ett ömsesidigt sekretessavtal för att skydda båda parter.'),
    ('We map your growth potential', 'Vi kartlägger din tillväxtpotential'),
    ('New markets, product expansion, AI capabilities, technical debt reduction and competitive positioning — tailored to your company.', 'Nya marknader, produktexpansion, AI-förmågor, minskning av teknisk skuld och konkurrenspositionering – skräddarsytt för ditt bolag.'),
    ('We present it in person', 'Vi presenterar det personligen'),
    ('Your assessment is delivered in a private meeting, founder to founder. The insights are yours — no obligation, no pressure.', 'Din utvärdering levereras på ett privat möte, från grundare till grundare. Insikterna är dina – utan förpliktelser, utan press.'),
    ('Start your growth assessment', 'Starta din tillväxtutvärdering'),
    ('We review every application personally. All information is treated as strictly confidential.', 'Vi granskar varje ansökan personligen. All information behandlas strikt konfidentiellt.'),
    ('Your role', 'Din roll'),
    ('Founder & CEO', 'Grundare & vd'),
    ('Company name', 'Företagsnamn'),
    ('What does your company do?', 'Vad gör ditt bolag?'),
    ('Briefly describe your product and the public-sector customers you serve', 'Beskriv kortfattat din produkt och de offentliga kunder ni betjänar'),
    ('Submit application', 'Skicka in ansökan'),
    ('Your application goes directly to Alexander Hübel, Group CEO. All information is confidential. We respond to every application within 3 business days.', 'Din ansökan går direkt till Alexander Hübel, koncernchef. All information är konfidentiell. Vi svarar på alla ansökningar inom 3 arbetsdagar.'),
    ('What do founders who joined say?', 'Vad säger grundare som har anslutit?'),
    ("Don't take our word for it", 'Ta inte bara vårt ord för det'),
    ('Every application is reviewed personally by our CEO', 'Varje ansökan granskas personligen av vår vd'),
    ('A leading software platform for the Swedish personal-care sector — scheduling, reporting, communication and payroll in one secure system.', 'En ledande mjukvaruplattform för den svenska personliga assistansen — schemaläggning, rapportering, kommunikation och lön i ett säkert system.'),
    ('Associations / NGOs', 'Föreningar / NGO:er'),
    ('SBS Manager — a complete application-management system for grants and sponsorships from foundations, funds and grant providers.', 'SBS Manager — ett komplett ansökningssystem för bidrag och sponsring från stiftelser, fonder och anslagsgivare.'),
    ('Apuraha4 automates the full grant lifecycle — applications, decisions, payments, reporting — saving time and improving transparency.', 'Apuraha4 automatiserar hela bidragscykeln — ansökningar, beslut, betalningar, rapportering — sparar tid och förbättrar transparensen.'),
    ('Healthcare', 'Sjukvård'),
    ('Sotender — an easy-to-use mobile app connecting healthcare workers with open shifts, with measurable impact for providers and staff.', 'Sotender — en lättanvänd mobilapp som kopplar ihop vårdpersonal med lediga pass, med mätbar effekt för vårdgivare och personal.'),
    ('Municipalities', 'Kommuner'),
    ('EMBRACE — a powerful, easy-to-use platform for municipalities and police authorities in daily crime-prevention and safety work.', 'EMBRACE — en kraftfull, lättanvänd plattform för kommuner och polismyndigheter i det dagliga brottsförebyggande och trygghetsskapande arbetet.'),
    ("Thank you for your application. Alexander will be in touch personally within a few business days.", "Tack för din ansökan. Alexander kommer att höra av sig personligen inom ett par arbetsdagar.")
]

replacements_why_publix = replacements_index + [
    ('Why PubliX — The permanent home for public-sector SaaS founders', 'Varför PubliX — Det permanenta hemmet för SaaS-grundare inom offentlig sektor'),
    ('PubliX Group is a permanent owner of Nordic public-sector SaaS companies. No forced exits, shared customers, embedded AI capabilities. Learn why founders choose PubliX.', 'PubliX Group är en permanent ägare av nordiska SaaS-bolag inom offentlig sektor. Inga framtvingade exits, gemensamma kunder, inbyggda AI-förmågor. Läs om varför grundare väljer PubliX.'),
    ('Are you a founder wondering what comes next?', 'Är du en grundare som funderar på vad som kommer härnäst?'),
    ("You've spent years building something meaningful. We think that deserves a permanent home — not a three-year flip.", 'Du har ägnat år åt att bygga något betydelsefullt. Vi tycker att det förtjänar ett permanent hem – inte en treårig försäljning.'),
    ('See our process', 'Se vår process'),
    ('CEO to founder', 'Vd till grundare'),
    ('Ready to scale but missing some pieces?', 'Redo att skala upp men saknar några pusselbitar?'),
    ('You built it. We help you grow it further.', 'Du byggde det. Vi hjälper dig att växa det vidare.'),
    ("You've built a great company. You know your market, your customers and your organisation — and we trust you to continue leading the company you founded. That doesn't change.", 'Du har byggt ett fantastiskt bolag. Du känner din marknad, dina kunder och din organisation – och vi litar på att du fortsätter leda det bolag du grundade. Det förändras inte.'),
    ("What changes is what's around you. The barriers that have held you back — a local market, technical debt, lack of AI capability, doing everything yourself — those start to disappear. PubliX gives you the <strong>resources, the network, and the community</strong> to take the next step.", 'Det som förändras är det runt omkring dig. Barriärerna som har hållit dig tillbaka – en lokal marknad, teknisk skuld, brist på AI-förmåga, att göra allting själv – börjar försvinna. PubliX ger dig <strong>resurserna, nätverket och gemenskapen</strong> för att ta nästa steg.'),
    ("We're not a fund with a countdown clock. We're a <strong>permanent owner</strong> — backed by Aspira Partners, who share our long-term conviction. Your next chapter starts here, and there's no artificial end date.", 'Vi är inte en fond med en nedräkningsklocka. Vi är en <strong>permanent ägare</strong> – uppbackade av Aspira Partners, som delar vår långsiktiga övertygelse. Ditt nästa kapitel börjar här, och det finns inget artificiellt slutdatum.'),
    ('What does joining PubliX actually mean?', 'Vad innebär det egentligen att ansluta sig till PubliX?'),
    ('A permanent home, real AI, and shared customers', 'Ett permanent hem, riktig AI och gemensamma kunder'),
    ('A permanent home', 'Ett permanent hem'),
    ('No forced exits, no artificial timelines. PubliX is a permanent owner — backed by Aspira Partners, who share our long-term conviction. Your company grows at its own pace.', 'Inga framtvingade exits, inga artificiella tidslinjer. PubliX är en permanent ägare – uppbackade av Aspira Partners, som delar vår långsiktiga övertygelse. Ditt bolag växer i sin egen takt.'),
    ('AI-powered growth', 'AI-driven tillväxt'),
    ('Every company gets a tailored AI roadmap within 90 days. From product features to process automation — we embed capabilities your company couldn\'t build alone.', 'Varje bolag får en skräddarsydd AI-färdplan inom 90 dagar. Från produktfunktioner till processautomation – vi bygger in förmågor som ditt bolag inte kunde bygga på egen hand.'),
    ('Public sector DNA', 'Offentlig sektors DNA'),
    ('We only work in one vertical. That means shared procurement expertise, shared customers, and colleagues who understand framework agreements, not just ARR.', 'Vi arbetar endast i en vertikal. Det innebär gemensam upphandlingsexpertis, gemensamma kunder och kollegor som förstår ramavtal, inte bara ARR.'),
    ('Does it actually work?', 'Fungerar det faktiskt?'),
    ('Results, not promises', 'Resultat, inte löften'),
    ('ARR improvement — AI-powered grant matching drove measurable revenue growth within 6 months', 'ARR-förbättring — AI-driven bidragsmatchning drev mätbar omsättningstillväxt inom 6 månader'),
    ('Annual savings — operational automation freed resources to reinvest directly into product', 'Årliga besparingar — operativ automation frigjorde resurser för att återinvestera direkt i produkten'),
    ('From initial requirement to signed public sector customer — fastest product launch in PubliX history', 'Från initialt krav till påskriven kund i offentlig sektor — snabbaste produktlanseringen i PubliX historia'),
    ('All OpCos', 'Alla dotterbolag'),
    ('Developer capacity freed — AI-assisted tools deployed across every company', 'Frigjord utvecklarkapacitet — AI-stödda verktyg driftsatta i varje bolag'),
    ('What does the journey look like?', 'Hur ser resan ut?'),
    ('From first call to day one in 3–5 months', 'Från första samtalet till dag ett på 3–5 månader'),
    ('No surprises, no hidden agendas. Here’s exactly what happens, step by step.', 'Inga överraskningar, inga dolda agendor. Här är exakt vad som händer, steg för steg.'),
    ('1. First conversation', '1. Första samtalet'),
    ('~1 hour', '~1 timme'),
    ('A relaxed, confidential conversation between you and our leadership. No PowerPoints, no pressure. We want to understand your company, your journey and what you’re thinking about. You’ll get a clear sense of who we are and how we work.', 'Ett avslappnat, konfidentiellt samtal mellan dig och vår ledning. Inga PowerPoint-presentationer, ingen press. Vi vill förstå ditt bolag, din resa och vad du funderar på. Du får en tydlig bild av vilka vi är och hur vi arbetar.'),
    ('2. Getting to know each other', '2. Lära känna varandra'),
    ('2–4 weeks', '2–4 veckor'),
    ('We sign a mutual NDA and start learning about your business in more depth — financials, customers, product, team. You learn more about us. This is a two-way evaluation, and we take it seriously.', 'Vi skriver under ett ömsesidigt sekretessavtal och börjar lära oss mer om din verksamhet på djupet – ekonomi, kunder, produkt, team. Du lär dig mer om oss. Detta är en tvåvägsutvärdering och vi tar den på allvar.'),
    ('3. Value creation plan &amp; indicative offer', '3. Värdeskapande plan &amp; indikativt erbjudande'),
    ('~2 weeks', '~2 veckor'),
    ('We present a tailored value creation plan — how your company could scale through new markets, shared customers, AI capabilities and reduced technical debt as part of PubliX. Alongside it, you receive an indicative offer with transparent valuation methodology. No complex structures.', 'Vi presenterar en skräddarsydd plan för värdeskapande – hur ditt bolag skulle kunna skala genom nya marknader, gemensamma kunder, AI-förmågor och minskad teknisk skuld som en del av PubliX. Utöver det får du ett indikativt erbjudande med en transparent värderingsmodell. Inga komplicerade strukturer.'),
    ('4. Due diligence', '4. Företagsbesiktning (Due diligence)'),
    ('4–8 weeks', '4–8 veckor'),
    ('A structured process where we verify the details together. We use experienced advisors and keep the process respectful of your time. Most founders say this is where they realised we were different — we treat DD as collaboration, not interrogation.', 'En strukturerad process där vi tillsammans verifierar detaljerna. Vi anlitar erfarna rådgivare och ser till att processen respekterar din tid. De flesta grundare säger att det är här de insåg att vi var annorlunda – vi hanterar DD som ett samarbete, inte ett förhör.'),
    ('5. Welcome to PubliX', '5. Välkommen till PubliX'),
    ('Day one', 'Dag ett'),
    ('You join a group of founder-led companies building for the public good. Your team, your brand, your office — all stay. What changes: you get shared AI capabilities, AI automation of internal processes, cross-selling opportunities, and colleagues who understand your market.', 'Du ansluter dig till en grupp av grundarledda bolag som bygger för samhällsnyttan. Ditt team, ditt varumärke, ditt kontor – allt blir kvar. Det som förändras: du får tillgång till delade AI-förmågor, AI-automatisering av interna processer, korsförsäljningsmöjligheter och kollegor som förstår din marknad.'),
    ('Still have questions?', 'Har du fortfarande frågor?'),
    ('We believe in full transparency', 'Vi tror på full transparens'),
    ('What happens to my team after an acquisition?', 'Vad händer med mitt team efter ett förvärv?'),
    ('Nothing. Your team stays. We don’t do layoffs, we don’t "streamline" headcount, and we don’t merge teams into some shared services centre. Your people are what make your company valuable — why would we change that?', 'Ingenting. Ditt team stannar kvar. Vi gör inga uppsägningar, vi "effektiviserar" inte antalet anställda och vi slår inte ihop team i något gemensamt servicecenter. Det är dina medarbetare som gör ditt bolag värdefullt – varför skulle vi ändra på det?'),
    ('Will you change my product?', 'Kommer ni att ändra på min produkt?'),
    ('No. Product decisions stay with you and your team. We’ll offer AI capabilities, engineering support, and strategic input — but the roadmap is yours. We’re operators, not product managers.', 'Nej. Produktbesluten stannar hos dig och ditt team. Vi kommer att erbjuda AI-förmågor, tekniskt stöd och strategiska insikter – men produktplanen är er. Vi är operatörer, inte produktchefer.'),
    ('How long does the whole process take?', 'Hur lång tid tar hela processen?'),
    ('Typically 3–5 months from first conversation to close. We don’t rush, but we don’t drag things out either. The timeline depends largely on due diligence complexity and your own readiness.', 'Typiskt sett 3–5 månader från första samtalet till avslut. Vi stressar inte, men vi drar inte ut på tiden heller. Tidsplanen beror till stor del på hur komplex företagsbesiktningen är och din egen beredskap.'),
    ('Can I stay on as CEO?', 'Kan jag sitta kvar som vd?'),
    ('Yes — and we strongly prefer it. Every company in our portfolio is run by its original founder or a hand-picked successor. We invest in founders, not despite them.', 'Ja – och vi föredrar det starkt. Varje bolag i vår portfölj drivs av sin ursprungliga grundare eller en handplockad efterträdare. Vi investerar i grundare, inte trots dem.'),
    ('What if I want to step back eventually?', 'Vad händer om jag vill kliva åt sidan så småningom?'),
    ('That’s fine too. We’ll work together on a transition plan that protects your team and your company’s culture. There’s no cliff edge — you choose the pace.', 'Det går också bra. Vi arbetar tillsammans fram en övergångsplan som skyddar ditt team och ditt bolags kultur. Det finns inga tvära kast – du väljer själv takten.'),
    ('How do you value my company?', 'Hur värderar ni mitt bolag?'),
    ('We use a transparent, market-based methodology that considers recurring revenue, growth trajectory, market position, customer quality and team strength. You’ll see the full model — no black boxes. We present our valuation in person so you can challenge every assumption.', 'Vi använder en transparent, marknadsbaserad metodik som tar hänsyn till återkommande intäkter, tillväxtkurva, marknadsposition, kundkvalitet och teamets styrka. Du får se hela modellen – inga dolda formler. Vi presenterar vår värdering personligen så att du kan ifrågasätta varje antagande.'),
    ('Ready for a confidential conversation?', 'Redo för ett konfidentiellt samtal?'),
    ("A growth assessment is a serious, personalised analysis — not a sales pitch. It's yours to keep, whether we work together or not.", 'En tillväxtutvärdering är en seriös, personlig analys – ingen säljpitch. Den är din att behålla, oavsett om vi arbetar tillsammans eller inte.')
]

def translate_all():
    replace_in_file('about.html', replacements_about)
    replace_in_file('career.html', replacements_career)
    replace_in_file('companies.html', replacements_companies)
    replace_in_file('contact.html', replacements_contact)
    replace_in_file('news.html', replacements_news)
    replace_in_file('process.html', replacements_process)
    replace_in_file('why-publix.html', replacements_why_publix)
    replace_in_file('index.html', replacements_index)

translate_all()
print("Translation complete.")
